---
title: "NYC_Airbnb"
author: "Xiao Liu"
date: "2/7/2019"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
setwd('~/Downloads')
library(readr)
library(dplyr)
require(dplyr)
library(ggplot2)

# read data

nyc_listings = read.csv('listings.csv', sep = ",", na.strings = c("", "NA", "N/A")) #49056*96

### preprocessing 

cols_to_keep = c(
  'description', 
  'property_type', 'room_type', 'accommodates',
  'bathrooms', 'bedrooms', 'beds', 'square_feet',
  'price', 'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
  'availability_365', 'reviews_per_month', 'latitude', 'longitude', 'bed_type',
  'amenities')

nyc_listings = nyc_listings[cols_to_keep]

for (x in c(which(colnames(nyc_listings) %in% c("price", "cleaning_fee", 
                                                "extra_people")))){
  nyc_listings[,x] = as.numeric(gsub("\\$|,", "", nyc_listings[,x]))}
```


```{r}
# remove cols which have more than 80% missing values
nyc_listings = nyc_listings %>% dplyr::select(-which(colSums(is.na(nyc_listings))/dim(nyc_listings)[1] > 0.8)) 
```


```{r}
# make sure they are highly available 
nyc_listings = nyc_listings[which(nyc_listings$availability_365 > 60),]     #25427 obs
```

### Price Histogram

```{r}
library(plotly)
plot_ly(nyc_listings, x = ~price, type = 'box') 

#fit = density(nyc_listings[which(nyc_listings$price<=1000),]$price)
plot_ly(nyc_listings[which(nyc_listings$price<=1000),], x = ~price, type = 'histogram')  

```


```{r}
length(which(nyc_listings$price>372))/length(nyc_listings$price)
```

Only 6% observations has price larger than 372.


```{r}
plot_ly(nyc_listings, x = ~beds, type = 'histogram')  
```

Most properties have one available bed.


```{r}
df_bath = as.data.frame(table(nyc_listings$bathrooms))
plot_ly(df_bath, labels = ~Var1, values = ~Freq , type = 'pie') 
```

```{r}
df_bedrooms = as.data.frame(table(nyc_listings$bedrooms))
plot_ly(df_bedrooms, labels = ~Var1, values = ~Freq , type = 'pie') 
```

```{r}
plot_ly(nyc_listings, x = ~property_type, type = 'histogram')  
```

```{r}
plot_ly(nyc_listings, x = ~room_type, type = 'histogram')  
```

```{r}
plot_ly(nyc_listings, x = ~accommodates, type = 'histogram')  
```


```{r}
plot_ly(nyc_listings, x = ~cleaning_fee, type = 'box') 
```

```{r}
plot_ly(nyc_listings, x = ~guests_included, type = 'histogram') 
```

```{r}



```

